<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>    <UseWPF>true</UseWPF>
    <RootNamespace>BetterDesktop.Tools.ShellComponentsPlayground</RootNamespace>
    <AssemblyName>BetterDesktop.Tools.ShellComponentsPlayground</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\packages\kernel\kernel\BetterDesktop.Kernel.csproj" />
    <ProjectReference Include="..\..\packages\kernel\kernel-timer\BetterDesktop.Kernel.Timer.csproj" />
    <ProjectReference Include="..\..\packages\shell\shell-core\BetterDesktop.Shell.Core.csproj" />
    <ProjectReference Include="..\..\packages\shell\shell-settings\BetterDesktop.Shell.Settings.csproj" />
    <ProjectReference Include="..\..\packages\shell\shell-status\BetterDesktop.Shell.Status.csproj" />
    <ProjectReference Include="..\..\packages\shell\shell-menu-bar\BetterDesktop.Shell.MenuBar.csproj" />
  </ItemGroup>

</Project>
